# Generated by Django 4.2 on 2023-04-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='panzofi',
            fields=[
                ('cod_panzofi', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.URLField()),
                ('title', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('cod_rol', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('cod_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('date_session', models.DateTimeField(null=True)),
                ('time_session', models.TimeField(null=True)),
                ('button1', models.IntegerField(null=True)),
                ('button2', models.IntegerField(null=True)),
                ('cod_rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appiPanzofi.rol')),
            ],
        ),
    ]
