# Generated by Django 4.2 on 2023-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiPanzofi', '0002_alter_usuario_cod_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panzofi',
            name='logo',
            field=models.BinaryField(),
        ),
    ]
