# Generated by Django 4.2 on 2023-04-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiPanzofi', '0007_alter_panzofi_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panzofi',
            name='logo',
            field=models.BinaryField(null=True),
        ),
    ]
